// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"database/sql"
)

type User struct {
	Uuid      sql.NullString `json:"uuid"`
	Email     sql.NullString `json:"email"`
	Password  sql.NullString `json:"password"`
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	Nickname  sql.NullString `json:"nickname"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}
